### ISSUE TITLE
unable to upload bigger files then 1MB

### ISSUE THREAD

**Issue by mcschnei** [la-cc/anything-llm-helm-chart#2]
hi,

i have a problem that if i try to upload a bigger file then 1MB, it runs for ever (no error or anything else). The issue is at uploading stage, not embedding stage (to the workspace). 

attached are the file taht i use as a example but get the same issue with lots of other files s well
[EB-3-key-ingredients.pdf](https://github.com/user-attachments/files/16507105/EB-3-key-ingredients.pdf)

Thanks for your help

**Comment by la-cc** [comment]
Hi @marco-zadara, 

is a valid point. 
It is best to open the issue directly in the[ Anything-LLM app repo](https://github.com/Mintplex-Labs/anything-llm). Perhaps there is a flag that restricts this. 

Unfortunately, the logs don't show anything, it looks like it was blocked previously (before chunking through the embedder).

Until you have an answer, you can solve it via "fetch website".  I will also try to establish contact.

**Comment by mcschnei** [comment]
I found the problem. it has nothing todo with your anything-LLM chart. I forgot to add nginx.ingress.kubernetes.io/proxy-body-size to my nginx ingress ressource. the default is 1m and that's the reason why I run in the issue. 
thanks for your help and great work!!!
