### ISSUE TITLE
Add support for configuring ingress.ingressClassName

### ISSUE THREAD

**Issue by vdamov** [la-cc/anything-llm-helm-chart#3]
Here’s a suggested GitHub issue template you can use for requesting the functionality to change `ingress.ingressClassName` in the Helm chart:

---

**Title:** Feature Request: Add support for configuring `ingress.ingressClassName`

**Description:**
Currently, the Helm chart does not provide a way to customize the `ingressClassName` for the Ingress resource. It would be helpful to add this functionality, allowing users to specify a custom `ingressClassName` for better control over which ingress controller handles the traffic.

**Proposed Solution:**
Add an optional parameter `ingress.ingressClassName` to the `values.yaml` file. This parameter should default to `null` (or a sensible default), and when set, it should be used in the `Ingress` resource definition.

Example:

In `values.yaml`:
```yaml
ingress:
  enabled: true
  ingressClassName: "" # Default to null or provide an empty string
```

In the `Ingress` manifest:
```yaml
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "" }}
```

**Use Cases:**
- Users who are working in environments with multiple ingress controllers.
- Users who want to specify a different ingress controller for specific services.

**Additional Context:**
This would provide more flexibility for deploying the Helm chart in Kubernetes clusters that use multiple ingress controllers.

---

You can modify this further to match your style or any additional details you’d like to include before submitting it to the repository.

**Comment by la-cc** [comment]
Thank you so much for the valuable input! 

The suggested template aligns perfectly with my style of implementation, and I've already incorporated it. The idea to add support for ingress.ingressClassName in the Helm chart is exactly what was needed to provide better flexibility for environments with multiple ingress controllers. 

I really appreciate the detailed proposal, especially the clarity around the default behavior and use cases. It’s now implemented as proposed!
